version: 999.{branch}-{build}
clone_folder: c:\qreal
#test: off

clone_depth: 1
#shallow_clone: true

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    PYTHON_PATH: C:\Python27
    PYTHON_LIB: C:\Python27\libs
    CCACHE_DIR: C:\ccache.cache
    BUILD_DIR: '%APPVEYOR_BUILD_FOLDER%\.build'
    PROJECT_FILE: qrealRobotsTest
    TEST_SUITE: .\robots_kitBase_unittests.exe && .\robots_interpreterCore_unittests.exe && .\robots_twoDModel_unittests.exe && .\trik-v62-qts-generator-tests.exe && .\robots_utils_unittests.exe"
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9
  matrix:
#    - PROJECT_FILE: qreal
      - MINGW: C:\Qt\Tools\mingw530_32
        QTDIR: C:\Qt\5.11.1\mingw53_32
      - MINGW: C:\Qt\Tools\mingw492_32
        QTDIR: C:\Qt\5.6.3\mingw49_32

configuration:
#  - debug
  - release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%CCACHE_DIR%'
  - '%BUILD_DIR%'

install:
  - set PATH=%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - pacman --verbose --noconfirm --sync ccache rsync curl
#--refresh --sysupgrade --ask=20
  - ccache.exe -V || appveyor DownloadFile "http://alam.srb2.org/ccache.exe" -FileName "ccache.exe" && xcopy /Y /V /I ccache.exe %MINGW%\bin && ccache -V
  - ccache -p || echo "Failed to print ccache config (missing -p option)"
  - if not exist %BUILD_DIR% mkdir %BUILD_DIR%
  - du -sh %BUILD_DIR% %CCACHE_DIR%
  - ccache -M 900M
  - which g++
  - g++ --version


before_build:
  - git submodule update --init --recursive
  - curl https://raw.githubusercontent.com/MestreLion/git-tools/master/git-restore-mtime-bare > .fix-mtime.py
  - python .fix-mtime.py
  - git submodule foreach --recursive python %cd%\.fix-mtime.py


build_script:
  - cd %BUILD_DIR%
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro -spec win32-g++ CONFIG+=%CONFIGURATION% # QMAKE_CXX="ccache g++"
  - mingw32-make -j2 qmake_all
  - mingw32-make -j2 -k all

test_script:
  - echo %cd%
  - cd %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%
  - dir
  - cmd /c %TEST_SUITE%

on_finish:
  - ccache -s


artifacts:
 - path: bin\$(configuration)
   name: qreal-$(configuration)-$(PROJECT_FILE)
